package dns

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kompox/ssh-bastion/internal/storage"
)

type Alias struct {
	Source      string `json:"source"`
	Destination string `json:"destination"`
}

type Registry struct {
	store *storage.Store
}

func NewRegistry(store *storage.Store) *Registry {
	return &Registry{store: store}
}

func (r *Registry) AddAlias(source, destination string) error {
	source = strings.TrimSpace(source)
	destination = strings.TrimSpace(destination)

	if source == "" || destination == "" {
		return fmt.Errorf("source and destination must be non-empty")
	}

	aliases, err := r.ListAliases()
	if err != nil {
		return err
	}

	for _, alias := range aliases {
		if alias.Source == source {
			return fmt.Errorf("alias already exists for source: %s", source)
		}
	}

	aliases = append(aliases, Alias{
		Source:      source,
		Destination: destination,
	})

	return r.saveAliases(aliases)
}

func (r *Registry) ListAliases() ([]Alias, error) {
	path := r.store.Path(filepath.Join("dns", "aliases.json"))

	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return []Alias{}, nil
	}
	if err != nil {
		return nil, err
	}

	var aliases []Alias
	if err := json.Unmarshal(data, &aliases); err != nil {
		return nil, err
	}

	return aliases, nil
}

func (r *Registry) DeleteAlias(source string) error {
	aliases, err := r.ListAliases()
	if err != nil {
		return err
	}

	var filtered []Alias
	for _, alias := range aliases {
		if alias.Source != source {
			filtered = append(filtered, alias)
		}
	}

	return r.saveAliases(filtered)
}

func (r *Registry) saveAliases(aliases []Alias) error {
	data, err := json.MarshalIndent(aliases, "", "  ")
	if err != nil {
		return err
	}

	return r.store.AtomicWrite(filepath.Join("dns", "aliases.json"), data)
}

func (r *Registry) RenderDnsmasqConf() error {
	aliases, err := r.ListAliases()
	if err != nil {
		return err
	}

	var lines []string
	lines = append(lines, "# Generated by ssh-bastion web app")
	lines = append(lines, "# Do not edit manually")
	lines = append(lines, "")

	for _, alias := range aliases {
		lines = append(lines, fmt.Sprintf("cname=%s,%s", alias.Source, alias.Destination))
	}

	content := strings.Join(lines, "\n")
	if content != "" {
		content += "\n"
	}

	return r.store.AtomicWrite(filepath.Join("dns", "dnsmasq.d", "generated.conf"), []byte(content))
}
