#!/bin/sh
set -eu

DATA_DIR="${SSHBASTION_DATA_DIR:-/data}"
AUTHORIZED_KEYS_FILE="${DATA_DIR}/authorized_keys/jump"
HOST_KEYS_DIR="${DATA_DIR}/ssh"

# Only the sshd container should resolve via dnsmasq (running in the shared
# network namespace). Docker does not allow setting `dns:` when `network_mode`
# is set to `service:...`, so configure resolv.conf here instead.
if [ -n "${SSHBASTION_SSHD_NAMESERVER:-}" ]; then
	if ! {
		echo "nameserver ${SSHBASTION_SSHD_NAMESERVER}"
		echo "options timeout:1 attempts:5"
	} > /etc/resolv.conf; then
		echo "WARN: failed to write /etc/resolv.conf (nameserver=${SSHBASTION_SSHD_NAMESERVER}); sshd DNS may not use dnsmasq" >&2
	fi
fi

mkdir -p "${DATA_DIR}/authorized_keys" "${HOST_KEYS_DIR}" /run/sshd

# sshd enforces StrictModes by default. Ensure path components are not
# group/other-writable, otherwise publickey auth is refused.
chmod 0755 "${DATA_DIR}" || true
chmod 0755 "${DATA_DIR}/authorized_keys" || true

# Ensure the shared SSH user exists and is allowed to log in.
# On Alpine, creating a user without a password can still leave the account
# in a "locked" state, which sshd rejects even for publickey auth.
if ! id -u jump >/dev/null 2>&1; then
	adduser -D -h /home/jump -s /bin/sh jump >/dev/null 2>&1 || true
fi

# Try to ensure the account is unlocked (best-effort; depends on passwd implementation).
passwd -u jump >/dev/null 2>&1 || true
passwd -d jump >/dev/null 2>&1 || true

# Ensure the authorized_keys file exists (it is generated by the web app).
# Create an empty file so sshd can start even before any key is registered.
touch "${AUTHORIZED_KEYS_FILE}"
chmod 0644 "${AUTHORIZED_KEYS_FILE}" || true

# Generate host keys under /data so they persist across container restarts.
# Keep the set minimal but compatible.
if [ ! -f "${HOST_KEYS_DIR}/ssh_host_ed25519_key" ]; then
	ssh-keygen -q -t ed25519 -f "${HOST_KEYS_DIR}/ssh_host_ed25519_key" -N "" >/dev/null 2>&1
fi
if [ ! -f "${HOST_KEYS_DIR}/ssh_host_rsa_key" ]; then
	ssh-keygen -q -t rsa -b 3072 -f "${HOST_KEYS_DIR}/ssh_host_rsa_key" -N "" >/dev/null 2>&1
fi
chmod 0600 "${HOST_KEYS_DIR}/ssh_host_ed25519_key" "${HOST_KEYS_DIR}/ssh_host_rsa_key" || true

cat > /tmp/sshd_config <<EOF
Port 22
ListenAddress 0.0.0.0

HostKey ${HOST_KEYS_DIR}/ssh_host_ed25519_key
HostKey ${HOST_KEYS_DIR}/ssh_host_rsa_key

PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
PubkeyAuthentication yes
AuthenticationMethods publickey

AuthorizedKeysFile ${AUTHORIZED_KEYS_FILE}

AllowTcpForwarding yes
X11Forwarding no
AllowAgentForwarding no
PermitTTY no

UseDNS no
PrintMotd no
LogLevel INFO
Subsystem sftp internal-sftp
EOF

exec /usr/sbin/sshd -D -e -f /tmp/sshd_config
