#!/bin/sh
set -eu

DATA_DIR="${SSHBASTION_DATA_DIR:-/data}"
AUTHORIZED_KEYS_FILE="${DATA_DIR}/authorized_keys/jump"
HOST_KEYS_DIR="${DATA_DIR}/ssh"
FORWARDING_POLL_SECONDS="5"

SSHD_LOG_LEVEL="${SSHBASTION_SSHD_LOG_LEVEL:-INFO}"
case "${SSHD_LOG_LEVEL}" in
	QUIET|FATAL|ERROR|INFO|VERBOSE|DEBUG|DEBUG1|DEBUG2|DEBUG3)
		;;
	*)
		echo "WARN: invalid SSHBASTION_SSHD_LOG_LEVEL='${SSHD_LOG_LEVEL}', falling back to INFO" >&2
		SSHD_LOG_LEVEL="INFO"
		;;
esac

# Only the sshd container should resolve via dnsmasq (running in the shared
# network namespace). Docker does not allow setting `dns:` when `network_mode`
# is set to `service:...`, so configure resolv.conf here instead.
if [ -n "${SSHBASTION_SSHD_NAMESERVER:-}" ]; then
	if ! {
		echo "nameserver ${SSHBASTION_SSHD_NAMESERVER}"
		echo "options timeout:1 attempts:5"
	} > /etc/resolv.conf; then
		echo "WARN: failed to write /etc/resolv.conf (nameserver=${SSHBASTION_SSHD_NAMESERVER}); sshd DNS may not use dnsmasq" >&2
	fi
fi

mkdir -p "${DATA_DIR}/authorized_keys" "${HOST_KEYS_DIR}" /run/sshd

# sshd enforces StrictModes by default. Ensure path components are not
# group/other-writable, otherwise publickey auth is refused.
chmod 0755 "${DATA_DIR}" || true
chmod 0755 "${DATA_DIR}/authorized_keys" || true

# Ensure the authorized_keys file exists (it is generated by the web app).
# Create an empty file so sshd can start even before any key is registered.
touch "${AUTHORIZED_KEYS_FILE}"
chmod 0644 "${AUTHORIZED_KEYS_FILE}" || true

# Generate host keys under /data so they persist across container restarts.
# Keep the set minimal but compatible.
if [ ! -f "${HOST_KEYS_DIR}/ssh_host_ed25519_key" ]; then
	ssh-keygen -q -t ed25519 -f "${HOST_KEYS_DIR}/ssh_host_ed25519_key" -N "" >/dev/null 2>&1
fi
if [ ! -f "${HOST_KEYS_DIR}/ssh_host_rsa_key" ]; then
	ssh-keygen -q -t rsa -b 3072 -f "${HOST_KEYS_DIR}/ssh_host_rsa_key" -N "" >/dev/null 2>&1
fi
chmod 0600 "${HOST_KEYS_DIR}/ssh_host_ed25519_key" "${HOST_KEYS_DIR}/ssh_host_rsa_key" || true

/usr/local/bin/ssh-bastion sshd-config \
	-data-dir "${DATA_DIR}" \
	-authorized-keys-file "${AUTHORIZED_KEYS_FILE}" \
	-host-keys-dir "${HOST_KEYS_DIR}" \
	-log-level "${SSHD_LOG_LEVEL}" \
	> /tmp/sshd_config

if ! /usr/sbin/sshd -t -f /tmp/sshd_config; then
	echo "ERROR: initial sshd_config validation failed" >&2
	exit 1
fi

/usr/sbin/sshd -D -e -f /tmp/sshd_config &
sshd_pid="$!"

terminate() {
	if [ -n "${sshd_pid}" ] && kill -0 "${sshd_pid}" 2>/dev/null; then
		kill "${sshd_pid}" 2>/dev/null || true
		wait "${sshd_pid}" || true
	fi
	exit 0
}

trap terminate INT TERM

last_restart_generation="$(/usr/local/bin/ssh-bastion forwarding-restart-generation -data-dir "${DATA_DIR}" 2>/dev/null || echo 0)"

while true; do
	if ! kill -0 "${sshd_pid}" 2>/dev/null; then
		wait "${sshd_pid}" || exit $?
		exit 1
	fi

	restart_generation="$(/usr/local/bin/ssh-bastion forwarding-restart-generation -data-dir "${DATA_DIR}" 2>/dev/null || echo 0)"
	if [ "${restart_generation}" -gt "${last_restart_generation}" ]; then
		echo "INFO: restart requested (restartGeneration ${last_restart_generation} -> ${restart_generation})" >&2
		kill "${sshd_pid}" 2>/dev/null || true
		wait "${sshd_pid}" || true
		exit 0
	fi
	last_restart_generation="${restart_generation}"

	if /usr/local/bin/ssh-bastion sshd-config \
		-data-dir "${DATA_DIR}" \
		-authorized-keys-file "${AUTHORIZED_KEYS_FILE}" \
		-host-keys-dir "${HOST_KEYS_DIR}" \
		-log-level "${SSHD_LOG_LEVEL}" \
		> /tmp/sshd_config.new; then
		if ! cmp -s /tmp/sshd_config.new /tmp/sshd_config; then
			if /usr/sbin/sshd -t -f /tmp/sshd_config.new; then
				mv /tmp/sshd_config.new /tmp/sshd_config
				kill -HUP "${sshd_pid}" 2>/dev/null || true
				echo "INFO: reloaded sshd_config" >&2
			else
				echo "WARN: generated sshd_config failed validation; keeping previous config" >&2
				rm -f /tmp/sshd_config.new || true
			fi
		else
			rm -f /tmp/sshd_config.new || true
		fi
	else
		echo "WARN: failed to generate sshd_config; keeping previous config" >&2
		rm -f /tmp/sshd_config.new || true
	fi

	sleep "${FORWARDING_POLL_SECONDS}"
done
