//go:build e2e

package e2e_test

import (
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/miekg/dns"
)

func TestE2E_GenerateDnsmasqConf(t *testing.T) {
	httpBase := getEnvDefault("SSHBASTION_E2E_HTTP_BASE", "http://localhost:8080")
	dataDir := getDataDir()

	waitHTTP200(t, httpBase+"/", 60*time.Second)

	source := "e2e.local"
	destination := "ssh-bastion"

	client := &http.Client{
		Timeout: 10 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}

	form := url.Values{}
	form.Set("source", source)
	form.Set("destination", destination)

	resp, err := client.PostForm(httpBase+"/dns", form)
	if err != nil {
		t.Fatalf("POST /dns failed: %v", err)
	}
	defer resp.Body.Close()
	_, _ = io.ReadAll(resp.Body)

	if resp.StatusCode != http.StatusSeeOther {
		t.Fatalf("expected POST /dns to return 303, got %d", resp.StatusCode)
	}

	generated := filepath.Join(dataDir, "dns", "dnsmasq.d", "generated.conf")
	wantLine := fmt.Sprintf("cname=%s,%s", source, destination)
	content := waitReadFileContains(t, generated, wantLine, 10*time.Second)

	if !strings.Contains(content, "# Generated by ssh-bastion web app") {
		t.Fatalf("generated.conf missing header")
	}

	aliasesJSON := filepath.Join(dataDir, "dns", "aliases.json")
	_ = waitReadFileContains(t, aliasesJSON, source, 5*time.Second)
}

func TestE2E_DNSResolvesAlias(t *testing.T) {
	dnsAddr := getEnvDefault("SSHBASTION_E2E_DNS_ADDR", "127.0.0.1:5353")

	source := "e2e.local"
	destination := "ssh-bastion"

	wantCNAME := dns.Fqdn(destination)
	name := dns.Fqdn(source)

	client := &dns.Client{Timeout: 2 * time.Second}
	deadline := time.Now().Add(15 * time.Second)

	var lastErr error
	for time.Now().Before(deadline) {
		msg := new(dns.Msg)
		msg.SetQuestion(name, dns.TypeA)
		msg.RecursionDesired = true

		resp, _, err := client.Exchange(msg, dnsAddr)
		if err != nil {
			lastErr = err
			time.Sleep(250 * time.Millisecond)
			continue
		}
		if resp.Rcode != dns.RcodeSuccess {
			lastErr = fmt.Errorf("rcode=%s", dns.RcodeToString[resp.Rcode])
			time.Sleep(250 * time.Millisecond)
			continue
		}

		hasA := false
		cnameTarget := ""

		for _, rr := range append(append([]dns.RR{}, resp.Answer...), resp.Extra...) {
			switch v := rr.(type) {
			case *dns.CNAME:
				if strings.EqualFold(v.Hdr.Name, name) {
					cnameTarget = v.Target
				}
			case *dns.A:
				if v.A != nil {
					hasA = true
				}
			}
		}

		// If we got an A directly, we're done.
		if hasA {
			return
		}

		// dnsmasq may return only a CNAME and rely on the client to follow it.
		if cnameTarget != "" {
			normTarget := dns.Fqdn(strings.TrimSuffix(cnameTarget, "."))
			if !strings.EqualFold(normTarget, wantCNAME) {
				lastErr = fmt.Errorf("unexpected cname target: got %q want %q", cnameTarget, wantCNAME)
				time.Sleep(250 * time.Millisecond)
				continue
			}

			follow := new(dns.Msg)
			follow.SetQuestion(wantCNAME, dns.TypeA)
			follow.RecursionDesired = true

			followResp, _, err := client.Exchange(follow, dnsAddr)
			if err != nil {
				lastErr = fmt.Errorf("follow cname query failed: %w", err)
				time.Sleep(250 * time.Millisecond)
				continue
			}
			if followResp.Rcode != dns.RcodeSuccess {
				lastErr = fmt.Errorf("follow cname rcode=%s", dns.RcodeToString[followResp.Rcode])
				time.Sleep(250 * time.Millisecond)
				continue
			}

			for _, rr := range append(append([]dns.RR{}, followResp.Answer...), followResp.Extra...) {
				if a, ok := rr.(*dns.A); ok && a.A != nil {
					return
				}
			}

			lastErr = fmt.Errorf("cname target %q did not resolve to an A record", wantCNAME)
			time.Sleep(250 * time.Millisecond)
			continue
		}

		lastErr = fmt.Errorf("expected an A answer or a CNAME to %q", wantCNAME)
		time.Sleep(250 * time.Millisecond)
	}

	if lastErr == nil {
		lastErr = errors.New("timeout")
	}
	t.Fatalf("dns query did not meet expectations: %v", lastErr)
}

func waitHTTP200(t *testing.T, url string, timeout time.Duration) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	client := &http.Client{Timeout: 2 * time.Second}

	var lastErr error
	for time.Now().Before(deadline) {
		resp, err := client.Get(url)
		if err != nil {
			lastErr = err
			time.Sleep(250 * time.Millisecond)
			continue
		}
		_, _ = io.ReadAll(resp.Body)
		resp.Body.Close()
		if resp.StatusCode == http.StatusOK {
			return
		}
		lastErr = fmt.Errorf("status=%d", resp.StatusCode)
		time.Sleep(250 * time.Millisecond)
	}
	if lastErr == nil {
		lastErr = errors.New("timeout")
	}
	t.Fatalf("http not ready: %v", lastErr)
}

func waitReadFileContains(t *testing.T, path string, substr string, timeout time.Duration) string {
	t.Helper()
	deadline := time.Now().Add(timeout)
	var lastErr error
	for time.Now().Before(deadline) {
		b, err := os.ReadFile(path)
		if err != nil {
			lastErr = err
			time.Sleep(250 * time.Millisecond)
			continue
		}
		content := string(b)
		if strings.Contains(content, substr) {
			return content
		}
		lastErr = fmt.Errorf("missing %q", substr)
		time.Sleep(250 * time.Millisecond)
	}
	if lastErr == nil {
		lastErr = errors.New("timeout")
	}
	t.Fatalf("file %s not ready: %v", path, lastErr)
	return ""
}

func getDataDir() string {
	if v := os.Getenv("SSHBASTION_E2E_DATA_DIR"); v != "" {
		return v
	}
	// Tests run with package working dir typically at ./e2e.
	return filepath.Clean(filepath.Join("..", "_tmp", "data"))
}

func getEnvDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
